<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-17T04:06:07Z" name="Default suite" finished-at="2022-09-17T04:08:42Z" duration-ms="155002">
    <groups>
    </groups>
    <test started-at="2022-09-17T04:06:07Z" name="Default test" finished-at="2022-09-17T04:08:42Z" duration-ms="155002">
      <class name="Tests.RespondAssesmentTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:Tests.RespondAssesmentTest@6a4f1a55]" started-at="2022-09-17T12:06:07Z" name="setup" finished-at="2022-09-17T12:06:08Z" duration-ms="839" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Scenario1Test()[pri:0, instance:Tests.RespondAssesmentTest@6a4f1a55]" started-at="2022-09-17T12:06:08Z" name="Scenario1Test" finished-at="2022-09-17T12:06:45Z" duration-ms="37518" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario1Test -->
        <test-method is-config="true" signature="delete()[pri:0, instance:Tests.RespondAssesmentTest@6a4f1a55]" started-at="2022-09-17T12:06:45Z" name="delete" finished-at="2022-09-17T12:06:45Z" duration-ms="76" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Tests.RespondAssesmentTest@6a4f1a55]" started-at="2022-09-17T12:06:45Z" name="setup" finished-at="2022-09-17T12:06:46Z" duration-ms="742" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Scenario2Test()[pri:0, instance:Tests.RespondAssesmentTest@6a4f1a55]" started-at="2022-09-17T12:06:46Z" name="Scenario2Test" finished-at="2022-09-17T12:07:35Z" duration-ms="49013" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Search Results not working Correctly expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Search Results not working Correctly expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at Tests.RespondAssesmentTest.Scenario2Test(RespondAssesmentTest.java:48)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario2Test -->
        <test-method is-config="true" signature="delete()[pri:0, instance:Tests.RespondAssesmentTest@6a4f1a55]" started-at="2022-09-17T12:07:35Z" name="delete" finished-at="2022-09-17T12:07:35Z" duration-ms="78" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Tests.RespondAssesmentTest@6a4f1a55]" started-at="2022-09-17T12:07:35Z" name="setup" finished-at="2022-09-17T12:07:36Z" duration-ms="738" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Scenario3Test()[pri:0, instance:Tests.RespondAssesmentTest@6a4f1a55]" started-at="2022-09-17T12:07:36Z" name="Scenario3Test" finished-at="2022-09-17T12:08:42Z" duration-ms="65916" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario3Test -->
        <test-method is-config="true" signature="delete()[pri:0, instance:Tests.RespondAssesmentTest@6a4f1a55]" started-at="2022-09-17T12:08:42Z" name="delete" finished-at="2022-09-17T12:08:42Z" duration-ms="72" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- Tests.RespondAssesmentTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
